export interface Item{
    id:number;
    parentId:number;
    nameAr:string;
    nameEn:string;
    brandId:number;
    isSample:boolean;
    isDisabled:boolean;
    isDisabledInfoAr:string;
    isDisabledInfoEn:string;
    brnadNameAr:string;
    brandNameEn:string;
    categoryId:number;
    categoryNameAr:string;
    categoryNameEn:string;
    code:string;
    description:string;
    image:string;
}
